# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a Python base image with version 3.12 or above
FROM python:3.12-slim-bookworm

# Set working directory
WORKDIR /app

# Copy the necessary files
COPY pyproject.toml README.md rcon.py uv.lock /app/

# Install dependencies
RUN pip install --upgrade pip && pip install . 

# Copy the entire source code
COPY . /app

# Set the entry point for the Docker container
ENTRYPOINT ["python", "rcon.py"]
